name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting your first issue! Please make sure you are clear with what you are stating and provide examples. I will respond to you shortly.'
        pr-message: 'Thank you for submitting your first pull request! Please make sure you are clear with what you are submitting. I will get back to you if necessary.'
